# Shell variables
# Generated by 'wal'
wallpaper='/home/mxy/wallpaper/macos-monterey-wwdc-21-stock-5k-3840x2160-5584.jpg'

# Special
background='#180c4a'
foreground='#decfdd'
cursor='#decfdd'

# Colors
color0='#180c4a'
color1='#C6649E'
color2='#C86FA3'
color3='#9928CF'
color4='#B444C2'
color5='#CC8EB4'
color6='#CA99C6'
color7='#decfdd'
color8='#9b909a'
color9='#C6649E'
color10='#C86FA3'
color11='#9928CF'
color12='#B444C2'
color13='#CC8EB4'
color14='#CA99C6'
color15='#decfdd'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
